title: "My YouTube Blog"
description: "Every new YouTube upload becomes a blog post automatically."
baseurl: "/el-omari-lakbir"  # your repo name
url: "https://amineelom.github.io"  # your GitHub Pages domain
author: El Omari       
theme: minima
paginate: 10
paginate_path: "/page:num"

yt_feed_url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC3CuW4wKl8ttsalfFwbN5kA"


# Enable safe, GitHub-Pages-friendly plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag


# Navigation (you can add/remove items)
nav:
  - title: Home
    url: /
  - title: Articles
    url: /articles/




# Build output
sass:
  style: compressed