name: Update YouTube Blog Posts

# Trigger workflow daily (or adjust as needed)
on:
  schedule:
    - cron: '0 6 * * *'  # every day at 06:00 UTC
  workflow_dispatch:    # manual trigger

permissions:
  contents: write  # required to push changes

jobs:
  update-posts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser

    - name: Run RSS to posts script
      run: |
        python3 scripts/rss_to_posts.py

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add _posts
        if git diff-index --quiet HEAD; then
          echo "No changes to commit."
        else
          git commit -m "Update YouTube posts"
          git push origin main
        fi
